# Generated by Django 4.0.3 on 2022-12-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salpersonaldetails',
            old_name='lawyerType',
            new_name='Lawyer_Type',
        ),
    ]
