# Generated by Django 4.0.3 on 2022-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
