# Generated by Django 4.1.2 on 2022-11-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salpersonaldetails",
            name="cibil_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="salpersonaldetails",
            name="tenure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="master.tenure"
            ),
        ),
    ]
