# Generated by Django 4.0.2 on 2022-11-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0002_alter_product_and_policy_master_company_category_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='apf_approved_lender',
            field=models.ManyToManyField(to='master.BankName'),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='apf_approved_lender',
            field=models.ManyToManyField(to='master.BankName'),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='apf_approved_lender',
            field=models.ManyToManyField(to='master.BankName'),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='apf_approved_lender',
            field=models.ManyToManyField(to='master.BankName'),
        ),
        migrations.AlterField(
            model_name='salpersonaldetails',
            name='tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.tenure'),
        ),
    ]
