# Generated by Django 4.0.3 on 2022-09-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('account', '0002_leads_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
    ]
