# Generated by Django 4.1.2 on 2022-11-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
        ("account", "0002_customuser_alter_salpersonaldetails_cibil_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser", name="address", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.city",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="pincode",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="system_role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.role",
            ),
        ),
      
    ]
