# Generated by Django 4.0.3 on 2022-12-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_lawyertype_salpersonaldetails_lawyer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salincomedetails',
            name='Other_Bank_Name',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
