# Generated by Django 4.0.3 on 2022-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_salincomedetails_bonus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salpersonaldetails',
            name='retirement_proof',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='salincomedetails',
            name='bonus_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('No Bonus', 'No Bonus')], default=None, max_length=11),
        ),
    ]
