# Generated by Django 4.0.3 on 2022-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_leads_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='country',
        ),
        migrations.AlterField(
            model_name='leads',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
