# Generated by Django 4.0.3 on 2022-12-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_salpersonaldetails_retirement_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salotherincomes',
            name='rental_income',
        ),
    ]
