# Generated by Django 4.0.3 on 2022-09-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_studentdetails_country_alter_leads_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housewifedetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='retireddetails',
            name='country',
        ),
    ]
