# Generated by Django 4.1.2 on 2022-11-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
        ("account", "0004_alter_customuser_address_alter_customuser_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralprofile",
            name="full_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salpersonaldetails",
            name="cibil_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="salpersonaldetails",
            name="tenure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="master.tenure"
            ),
        ),
    ]
