# Generated by Django 4.0.3 on 2022-12-16 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_salincomedetails_net_sal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salincomedetails',
            name='net_sal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
