# Generated by Django 4.0.3 on 2022-09-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('account', '0005_remove_housewifedetails_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='country',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
    ]
