# Generated by Django 4.0.3 on 2022-09-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_leads_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='country',
        ),
    ]
