# Generated by Django 4.0.3 on 2022-12-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_salcompanydetails_other_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salcompanydetails',
            name='other_company_name',
            field=models.CharField(max_length=20),
        ),
    ]
