# Generated by Django 4.0.3 on 2022-09-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('account', '0007_remove_leads_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='country',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
    ]
