# Generated by Django 4.0.3 on 2022-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_salcompanydetails_other_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salcompanydetails',
            name='provident_fund_deduction',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='tds_deduction',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=None),
        ),
    ]
