# Generated by Django 4.0.3 on 2022-12-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_salincomedetails_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salincomedetails',
            name='Other_Bank_Name',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
