# Generated by Django 4.0.3 on 2022-12-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_salincomedetails_other_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salincomedetails',
            name='Other_Bank_Name',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
