# Generated by Django 4.0.3 on 2022-12-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_salincomedetails_other_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salotherincomes',
            name='rent_reflection_in_bank',
        ),
    ]
