# Generated by Django 4.0.3 on 2022-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_salexistingcreditcard_other_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salinvestments',
            name='amount',
            field=models.IntegerField(default=None),
        ),
    ]
