# Generated by Django 4.0.3 on 2022-12-19 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_saladditionalotherincomes_other_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salinvestments',
            name='investments',
        ),
        migrations.AddField(
            model_name='salinvestments',
            name='bank_sav_dep',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salinvestments',
            name='current_bal',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salinvestments',
            name='life_ins',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salinvestments',
            name='share_sec',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
