# Generated by Django 4.0.3 on 2022-12-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('account', '0013_salinvestments_other_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salcompanydetails',
            name='company_name',
            field=models.ForeignKey(blank=True, choices=[('Other', 'Other')], default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.companyname'),
        ),
    ]
