# Generated by Django 4.0.2 on 2022-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_product_and_policy_master_company_category_and_more'),
        ('HomeLoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlbasicdetails',
            name='company_type',
            field=models.ManyToManyField(to='master.CompanyType'),
        ),
        migrations.AlterField(
            model_name='hlbasicdetails',
            name='designation',
            field=models.ManyToManyField(to='master.DesignationType'),
        ),
        migrations.AlterField(
            model_name='hlproperty',
            name='negative_area',
            field=models.ManyToManyField(to='master.NegativeArea'),
        ),
        migrations.AlterField(
            model_name='hlproperty',
            name='property_type',
            field=models.ManyToManyField(to='master.PropertyType'),
        ),
        migrations.AlterField(
            model_name='hlproperty',
            name='room_type',
            field=models.ManyToManyField(to='master.RoomType'),
        ),
        migrations.AlterField(
            model_name='hlproperty',
            name='stage_of_construction',
            field=models.ManyToManyField(to='master.StageOfConstruction'),
        ),
    ]
