from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(Bank)
admin.site.register(Age)
admin.site.register(Cibil)
admin.site.register(Company)
admin.site.register(CostSheet)
admin.site.register(Customer)
admin.site.register(CustomerDesignation)
admin.site.register(CustomerNationality)
admin.site.register(Fees)
admin.site.register(Income)
admin.site.register(IncomeFoir)
admin.site.register(LoanTowardsValuation)
admin.site.register(LtvResale)
admin.site.register(NegativeEmployerProfile)
admin.site.register(Obligation)
admin.site.register(OtherDetails)
admin.site.register(OtherDetailsROI)
admin.site.register(Property)
admin.site.register(Remarks)
admin.site.register(BankCodes)
admin.site.register(ProductsAndPolicy)
admin.site.register(HlBasicDetails)
admin.site.register(HlIncome)
admin.site.register(HlIncomeFoir)
admin.site.register(HlObligation)
admin.site.register(HlOtherDetails)
admin.site.register(HlProperty)
admin.site.register(HlLoan_To_Value_Type_1)
admin.site.register(HlLoan_To_Value_Type_2)
