# Generated by Django 4.0.3 on 2022-10-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='is_degree',
            new_name='degree',
        ),
    ]
