# Generated by Django 4.1.2 on 2022-11-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="foircategory", name="gross_salary",),
        migrations.RemoveField(model_name="foircategory", name="net_salary",),
        migrations.RemoveField(model_name="multipliercategory", name="gross_salary",),
        migrations.RemoveField(model_name="multipliercategory", name="net_salary",),
    ]
