# Generated by Django 4.0.2 on 2022-11-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_and_policy_master',
            name='company_category',
            field=models.ManyToManyField(to='master.CompanyCategory'),
        ),
        migrations.AlterField(
            model_name='product_and_policy_master',
            name='company_type',
            field=models.ManyToManyField(to='master.CompanyType'),
        ),
        migrations.AlterField(
            model_name='product_and_policy_master',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_types', to='master.customertype'),
        ),
        migrations.AlterField(
            model_name='product_and_policy_master',
            name='foir',
            field=models.ManyToManyField(to='master.Foir'),
        ),
        migrations.AlterField(
            model_name='product_and_policy_master',
            name='residence_type',
            field=models.ManyToManyField(to='master.ResidenceType'),
        ),
        migrations.AlterField(
            model_name='product_and_policy_master',
            name='salary_type',
            field=models.ManyToManyField(to='master.SalaryType'),
        ),
        migrations.AlterField(
            model_name='product_and_policy_master',
            name='tenure',
            field=models.ManyToManyField(to='master.Tenure'),
        ),
    ]
