# Generated by Django 4.0.3 on 2022-12-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_salincomedetails_deduction_and_more'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeductionType',
        ),
    ]
