# Generated by Django 4.0.2 on 2022-11-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Commissiontype', models.CharField(max_length=100)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comissionrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Commissionrate', models.IntegerField(null=True)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(blank=True, null=True)),
                ('Commissiontype', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='master.commission')),
            ],
        ),
    ]
