# Generated by Django 4.1.2 on 2022-12-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_remove_foircategory_gross_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycatergorytypes",
            name="banks",
            field=models.ManyToManyField(to="master.bankname"),
        ),
    ]
