# Generated by Django 4.1.2 on 2022-12-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0003_companycatergorytypes_banks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Multiplier_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_salary", models.BigIntegerField()),
                ("max_salary", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PerTenure_Multiplier_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multiplier", models.IntegerField()),
                (
                    "associated_tenure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.tenure"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multiplier_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cocat_type", models.CharField(max_length=250)),
                (
                    "multiplier_data",
                    models.ManyToManyField(to="master.multiplier_data"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="multiplier_data",
            name="tenure_multipliers",
            field=models.ManyToManyField(to="master.pertenure_multiplier_data"),
        ),
        migrations.AddField(
            model_name="product_and_policy_master",
            name="multipier_info",
            field=models.ManyToManyField(to="master.multiplier_info"),
        ),
    ]
