# Generated by Django 4.1.2 on 2022-12-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0004_multiplier_data_pertenure_multiplier_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_and_policy_master",
            old_name="multipier_info",
            new_name="multiplier_info",
        ),
        migrations.RemoveField(model_name="product_and_policy_master", name="foir_bt",),
        migrations.RemoveField(
            model_name="product_and_policy_master", name="foir_fresh",
        ),
        migrations.RemoveField(
            model_name="product_and_policy_master", name="multiplier_bt",
        ),
        migrations.RemoveField(
            model_name="product_and_policy_master", name="multiplier_fresh",
        ),
        migrations.CreateModel(
            name="PerTenure_Foir_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foir", models.IntegerField()),
                (
                    "associated_tenure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.tenure"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Foir_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cocat_type", models.CharField(max_length=250)),
                (
                    "multiplier_data",
                    models.ManyToManyField(to="master.multiplier_data"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Foir_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_salary", models.BigIntegerField()),
                ("max_salary", models.BigIntegerField()),
                (
                    "tenure_foirs",
                    models.ManyToManyField(to="master.pertenure_multiplier_data"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product_and_policy_master",
            name="foir_info",
            field=models.ManyToManyField(to="master.foir_info"),
        ),
    ]
