# Generated by Django 4.1.2 on 2022-12-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "master",
            "0006_remove_foir_info_multiplier_data_foir_info_foir_data_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalRate_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_min_amount", models.BigIntegerField()),
                ("loan_max_amount", models.BigIntegerField()),
                ("rate_of_interest", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RateOfInterest_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_salary", models.BigIntegerField()),
                ("max_salary", models.BigIntegerField()),
                (
                    "additional_rate_info",
                    models.ManyToManyField(to="master.additionalrate_info"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product_and_policy_master",
            name="rate_of_interest",
            field=models.ManyToManyField(to="master.rateofinterest_info"),
        ),
    ]
