# Generated by Django 4.1.2 on 2022-12-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0008_remove_rateofinterest_info_max_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product_and_policy_master", name="tenure",),
    ]
